[plugin]
repository = "https://github.com/wolfcomp/KillFeed.git"
owners = [ "wolfcomp" ]
maintainers = [ "GayPotatoEmma" ]
project_path = ""
commit = "bbdaa36c32fcdd95a0e0522fea1d1038bf204089"
changelog = "## [1.2.0] (2026-12-18)\nInitial release for main repo\n\n## [1.1.0] (2025-12-24)\nAPI 14 update\n\n## [1.0.6] (2025-08-06)\nAPI 13 update\n\n## [1.0.5] (2025-08-05)\nFix null byte terminator issue\n\n## [1.0.4] (2025-08-03)\nSome cleanup before introducing config options\n\n## [1.0.3] (2025-08-01)\nFix index lookup crash\n\n## [1.0.2] (2025-08-01)\nAdd who last was targeted when death happened\n\n## [1.0.1] (2025-08-01)\nMade death message trigger from death packet\n\n## [1.0.0] (2025-08-01)\nInitial release on custom"
version = "1.2.0"
